services:
  redis:
    image: redis:latest
    container_name: redis-instance
    ports:
      - "6379:6379"
    command: ["sh", "-c", "redis-server --requirepass ${REDIS_PASSWORD}"]
    volumes:
      - redis-data:/data
    networks:
      - queue-network
    env_file:
      - .env

  celery:
    build:
      context: ../celery
      dockerfile: Dockerfile
    container_name: celery-app
    depends_on:
      - redis
    networks:
      - queue-network
    env_file:
      - .env

  fastapi:
    build:
      context: ../fast-api
      dockerfile: Dockerfile
    container_name: fastapi-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    networks:
      - queue-network
    depends_on:
      - redis
      - celery
    env_file:
      - .env

volumes:
  redis-data:
    driver: local

networks:
  queue-network:
    external: true
